"""Adiciona a tabela de favoritos

Revision ID: 04c2530f5e40
Revises: 005bfce3d894
Create Date: 2025-02-16 09:18:23.793879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04c2530f5e40'
down_revision: Union[str, None] = '005bfce3d894'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
