"""Remove rating field from review

Revision ID: 1f823a1d7f6a
Revises: acb73e80f30e
Create Date: 2024-12-22 18:28:53.449493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f823a1d7f6a'
down_revision: Union[str, None] = 'acb73e80f30e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'rating')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
