"""add google_id in book

Revision ID: 51f1d28f1393
Revises: f979dda6ba84
Create Date: 2024-12-01 20:13:04.849992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51f1d28f1393'
down_revision: Union[str, None] = 'f979dda6ba84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('google_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'google_id')
    # ### end Alembic commands ###
