"""Initial migration

Revision ID: 52fcbd4e6f08
Revises: 51f1d28f1393
Create Date: 2024-12-22 18:03:05.730362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52fcbd4e6f08'
down_revision: Union[str, None] = '51f1d28f1393'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
