"""Initial migration

Revision ID: 750cd08ea71c
Revises:
Create Date: 2024-11-03 15:33:38.824201

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '750cd08ea71c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
