"""create users table

Revision ID: 83942936740d
Revises: 750cd08ea71c
Create Date: 2024-11-03 16:53:59.223682

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '83942936740d'
down_revision: Union[str, None] = '750cd08ea71c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
