"""Add thumbnail column to books

Revision ID: 9a99f963d667
Revises: 1f823a1d7f6a
Create Date: 2025-02-15 18:01:56.445186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a99f963d667'
down_revision: Union[str, None] = '1f823a1d7f6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('thumbnail', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'thumbnail')
    # ### end Alembic commands ###
