"""Add new fields to reviews

Revision ID: acb73e80f30e
Revises: 52fcbd4e6f08
Create Date: 2024-12-22 18:20:52.456594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acb73e80f30e'
down_revision: Union[str, None] = '52fcbd4e6f08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('review_title', sa.String(), nullable=False))
    op.add_column('reviews', sa.Column('story_rating', sa.Integer(), nullable=False))
    op.add_column('reviews', sa.Column('style_rating', sa.Integer(), nullable=False))
    op.add_column('reviews', sa.Column('character_rating', sa.Integer(), nullable=False))
    op.add_column('reviews', sa.Column('overall_rating', sa.Float(), nullable=False))
    op.add_column('reviews', sa.Column('recommendation', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'recommendation')
    op.drop_column('reviews', 'overall_rating')
    op.drop_column('reviews', 'character_rating')
    op.drop_column('reviews', 'style_rating')
    op.drop_column('reviews', 'story_rating')
    op.drop_column('reviews', 'review_title')
    # ### end Alembic commands ###
