"""Create books and reviews tables

Revision ID: bfd39a5e40dd
Revises: e976ba8d16fe
Create Date: 2024-12-01 15:34:27.292269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfd39a5e40dd'
down_revision: Union[str, None] = 'e976ba8d16fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
